# Change these first
owner: jacobnicked # Your GitHub organization or username, where this repository lives
repo: jacobnicked-website-status # The name of this repository

sites:
  - name: Jacob Nicked
    url: https://jacobnicked.com
  - name: Jacob Nicked Blog
    url: https://blog.jacobnicked.com
  - name: Jacob Nicked Legacy
    url: https://legacy.jacobnicked.com
  - name: Jacob Nicked Tech
    url: https://tech.jacobnicked.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jacobnicked.com
  user-agent: jacobnicked
  # baseUrl: /your-repo-name
  logoUrl: https://jacobnicked.com/icon-pfp.jpg
  favicon: https://jacobnicked.com/icon-pfp.jpg
  name: Jacob Nicked Status
  theme: dark
  assignees:
    - jacobnicked
  introTitle: "Uptime monitor and status page"
  introMessage: Sample status page which uses **real-time** data from my [GitHub repository](https://github.com/jacobnicked/jacobnicked-website-status)
  navbar:
    - title: Home
      href: https://jacobnicked.com
    - title: Status
      href: /
    - title: Blog
      href: https://blog.jacobnicked.com
    - title: Legacy
      href: https://legacy.jacobnicked.com
    - title: Tech
      href: https://tech.jacobnicked.com
    - title: GitHub
      href: https://github.com/$OWNER
  metaTags:
    - name: "og:title"
      content: "Jacob Nicked Status"
    - name: "og:description"
      content: "Real-time uptime monitoring for my services"
    - name: "og:image"
      content: "https://jacobnicked.com/icon-pfp.jpg"
    - name: "og:url"
      content: "https://status.jacobnicked.com"
  links:
    - rel: me
      href: https://mas.to/@jacobnicked
    - rel: me 
      href: https://www.instagram.com/jacobnicked
    - rel: me 
      href: https://www.instagram.com/jacobnicked.pl
    - rel: me  
      href: https://www.instagram.com/jacobnicked  
    - rel: me  
      href: https://www.instagram.com/jacobnicked.pl  
    - rel: me  
      href: https://www.instagram.com/jacobnicked.2nd  
    - rel: me  
      href: https://www.instagram.com/jacobnickedbackup  
    - rel: me  
      href: https://www.instagram.com/jacobnicked.tech  
    - rel: me  
      href: https://www.instagram.com/sunniehauz  
    - rel: me  
      href: https://www.bsky.app/profile/jacobnicked.com  
    - rel: me  
      href: https://www.bsky.app/profile/2nd.jacobnicked.com  
    - rel: me  
      href: https://www.bsky.app/profile/pl.jacobnicked.com  
    - rel: me  
      href: https://www.bsky.app/profile/tech.jacobnicked.com  
    - rel: me  
      href: https://www.bsky.app/profile/sunniehauz.bsky.social  
    - rel: me  
      href: https://www.threads.com/@jacobnicked  
    - rel: me  
      href: https://www.threads.com/@jacobnicked.2nd  
    - rel: me  
      href: https://www.threads.com/@jacobnicked.pl  
    - rel: me  
      href: https://www.threads.com/@jacobnickedbackup  
    - rel: me  
      href: https://www.threads.com/@jacobnicked.tech  
    - rel: me  
      href: https://www.threads.com/@sunniehauz  
    - rel: me  
      href: https://www.tiktok.com/@jacobnicked  
    - rel: me  
      href: https://www.tiktok.com/@jacobnicked.2nd  
    - rel: me  
      href: https://www.tiktok.com/@jacobnicked.pl  
    - rel: me  
      href: https://www.tiktok.com/@sunniehauz  
    - rel: me  
      href: https://www.twitter.com/jacobnicked  
    - rel: me  
      href: https://www.twitter.com/jacobnicked2nd  
    - rel: me  
      href: https://www.twitter.com/jacobnicked_pl  
    - rel: me  
      href: https://www.twitter.com/jacobnickedtech  
    - rel: me  
      href: https://www.twitter.com/sunniehauz  
    - rel: me  
      href: https://www.youtube.com/@jacobnicked  
    - rel: me  
      href: https://www.youtube.com/@jacobnickedpl  
    - rel: me  
      href: https://www.youtube.com/@sunniehauz  
    - rel: me  
      href: https://www.twitch.tv/jacobnicked  
    - rel: me  
      href: https://www.jacobnicked.tumblr.com  
    - rel: me  
      href: https://www.xiaohongshu.com/user/profile/67868f230000000008018eba  
    - rel: me  
      href: https://mas.to/@jacobnicked  
    - rel: me  
      href: https://101010.pl/@jacobnicked_pl  
    - rel: me  
      href: https://mastodon.social/@jacobnickedtech  
    - rel: me  
      href: https://mastodon.social/@sunniehauz  
    - rel: me  
      href: https://www.pinterest.com/jacobnicked  
    - rel: me  
      href: https://www.facebook.com/jacobnicked  
    - rel: me  
      href: https://www.facebook.com/jacobnickedpl  
    - rel: me  
      href: https://www.github.com/jacobnicked  
    - rel: me  
      href: https://www.loops.video/@jacobnicked  
    - rel: me  
      href: https://www.loops.video/@jacobnicked.2nd  
    - rel: me  
      href: https://www.loops.video/@jacobnickedpl  
    - rel: me  
      href: https://www.loops.video/@jacobnickedtech  
    - rel: me  
      href: https://www.loops.video/@sunniehauz  
    - rel: me  
      href: https://www.pixelfed.social/@jacobnicked  
    - rel: me  
      href: https://www.pixelfed.social/@jacobnicked.2nd  
    - rel: me  
      href: https://www.pixelfed.social/@jacobnicked.tech  
    - rel: me  
      href: https://www.pixelfed.social/@sunniehauz  
    - rel: me  
      href: https://www.pixel.pol.social/@jacobnicked.pl  
    - rel: me  
      href: https://www.snapchat.com/add/jacobnicked  
    - rel: me  
      href: https://www.telegram.me/jacobnicked  
    - rel: me  
      href: https://www.telegram.me/jacobnickedpl  
    - rel: me  
      href: https://www.telegram.me/jacobnickedtech  
    - rel: me  
      href: https://www.telegram.me/jacobnickedtechstorage  
    - rel: me  
      href: https://www.telegram.me/sunniehauz  
    - rel: me  
      href: https://friendica.world/profile/jacobnicked  
    - rel: me  
      href: https://substack.com/@jacobnicked  
    - rel: me  
      href: https://pronouns.page/@jacobnicked  
    - rel: me  
      href: https://en.pronouns.page/@jacobnicked  
    - rel: me  
      href: https://pl.pronouns.page/@jacobnicked  
    - rel: me  
      href: https://zaimki.pl/@jacobnicked  
    - rel: me  
      href: https://www.wattpad.com/user/jacobnicked  
    - rel: me  
      href: https://digg.com/@jacobnicked

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
