# Change these first
owner: jacobnicked # Your GitHub organization or username, where this repository lives
repo: jacobnicked-website-status # The name of this repository

sites:
  - name: Jacob Nicked
    url: https://jacobnicked.site
  - name: Jacob Nicked Blog
    url: https://blog.jacobnicked.site
  - name: Jacob Nicked Tech
    url: https://tech.jacobnicked.site

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jacobnicked.site
  user-agent: jacobnicked
  # baseUrl: /your-repo-name
  logoUrl: https://jacobnicked.site/icon-pfp.jpg
  favicon: https://jacobnicked.site/icon-pfp.jpg
  name: Jacob Nicked Status
  theme: dark
  assignees:
    - jacobnicked
  introTitle: "Uptime monitor and status page"
  introMessage: Sample status page which uses **real-time** data from my [GitHub repository](https://github.com/jacobnicked/jacobnicked-website-status)
  # customHeadHtml: ""
  navbar:
    - title: Home
      href: https://jacobnicked.site
    - title: Status
      href: /
    - title: Blog
      href: https://blog.jacobnicked.site
    - title: Tech
      href: https://tech.jacobnicked.site
    - title: GitHub
      href: https://github.com/$OWNER
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
