# Change these first
owner: jacobnicked # Your GitHub organization or username, where this repository lives
repo: jacobnicked-website-status # The name of this repository

sites:
  - name: Jacob Nicked
    url: https://jacobnicked.com
  - name: Jacob Nicked Blog
    url: https://blog.jacobnicked.com
  - name: Jacob Nicked Legacy
    url: https://legacy.jacobnicked.com
  - name: Jacob Nicked Tech
    url: https://tech.jacobnicked.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jacobnicked.com
  user-agent: jacobnicked
  # baseUrl: /your-repo-name
  logoUrl: https://jacobnicked.com/icon-pfp.jpg
  favicon: https://jacobnicked.com/icon-pfp.jpg
  name: Jacob Nicked Status
  theme: dark
  assignees:
    - jacobnicked
  introTitle: "Uptime monitor and status page"
  introMessage: Sample status page which uses **real-time** data from my [GitHub repository](https://github.com/jacobnicked/jacobnicked-website-status)
  customHeadHtml: "<link href="https://mas.to/@jacobnicked" rel="me">"
  navbar:
    - title: Home
      href: https://jacobnicked.com
    - title: Status
      href: /
    - title: Blog
      href: https://blog.jacobnicked.com
    - title: Legacy
      href: https://legacy.jacobnicked.com
    - title: Tech
      href: https://tech.jacobnicked.com
    - title: GitHub
      href: https://github.com/$OWNER
  metaTags:
    - name: "og:title"
      content: "Jacob Nicked Status"
    - name: "og:description"
      content: "Real-time uptime monitoring for my services"
    - name: "og:image"
      content: "https://jacobnicked.com/icon-pfp.jpg"
    - name: "og:url"
      content: "https://status.jacobnicked.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
